mongodb:
  image: mongo:latest
  ports:
    - 27017:27017
nigradjobs:
  build: .
  links:
    - mongodb
  volumes:
    - ./src:/app
    - /app/node_modules # Stop node_modules being overridden by volume
nigradjobsapi:
  build: ./api
  links:
    - mongodb
  volumes:
    - ./api/src:/app
    - /app/node_modules # Stop node_modules being overridden by volume
  ports:
    - 3000:3000
